version: '3.4'
services:
  RSI_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI1_Active,RSI5_Active,RSI15_Active,RSI30_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI_Active.set
      TEST_REPORT_NAME: EA31337-RSI_Active
  RSI1_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI1_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI1_Active.set
      TEST_REPORT_NAME: EA31337-RSI1_Active
  RSI5_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI5_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI5_Active.set
      TEST_REPORT_NAME: EA31337-RSI5_Active
  RSI15_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI15_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI15_Active.set
      TEST_REPORT_NAME: EA31337-RSI15_Active
  RSI30_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI30_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI30_Active.set
      TEST_REPORT_NAME: EA31337-RSI30_Active
