language: generic
services:
  - docker
addons:
  apt:
    packages:
    - shellcheck
env:
  global:
  - CWD=$TRAVIS_BUILD_DIR
  - DOCKER_BUILDKIT=1
  matrix:
  - CMD='cd         All; for task in $(grep -o "^\s\s\w[^:]\+" docker-compose.yml); do docker-compose build --build-arg UID=$UID $task; docker-compose run $task; done'
  - CMD='cd       Boost; for task in $(grep -o "^\s\s\w[^:]\+" docker-compose.yml); do docker-compose build --build-arg UID=$UID $task; docker-compose run $task; done'
  - CMD='cd        Risk; for task in $(grep -o "^\s\s\w[^:]\+" docker-compose.yml); do docker-compose build --build-arg UID=$UID $task; docker-compose run $task; done'
  - CMD='cd  SmartQueue; for task in $(grep -o "^\s\s\w[^:]\+" docker-compose.yml); do docker-compose build --build-arg UID=$UID $task; docker-compose run $task; done'
matrix:
  fast_finish: true
before_install:
- ulimit -a && free -m
- docker --version
- docker images
install:
before_script:
- echo OPT_DRY_RUN=1 >> EA-Tester.ini
- echo OPT_TRACE=$OPT_TRACE >> EA-Tester.ini
script:
- echo $CMD
- eval $CMD
after_script:
- set +x
- git diff
after_success:
after_failure:
