version: '3.4'
services:
  Envelopes_TrailingStopMethod:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_TrailingStopMethod
      RUN_ON_SET: set_opt_params Envelopes_TrailingStopMethod 1 -27 0
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes_TrailingStopMethod
  Envelopes_TrailingProfitMethod:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_TrailingProfitMethod
      RUN_ON_SET: set_opt_params Envelopes_TrailingProfitMethod 1 -27 0
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes_TrailingProfitMethod
