version: '3.4'
services:
  Fractals_Shift:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Fractals_Shift
      RUN_ON_SET: set_opt_params Fractals_Shift $$(bc <<< "$$(input_get Fractals_Shift) - 1 * 2") $$(bc <<< "$$(input_get Fractals_Shift) + 1 * 2")
      SETFILE: /opt/sets/EURUSD/EA31337-Fractals_Shift.set
      TEST_REPORT_NAME: EA31337-Fractals_Shift
      BT_DEST: /opt/_results/EURUSD
