version: '3.4'
services:
  WPR_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR1_Active,WPR5_Active,WPR15_Active,WPR30_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR_Active.set
      TEST_REPORT_NAME: EA31337-WPR_Active
  WPR1_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR1_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR1_Active.set
      TEST_REPORT_NAME: EA31337-WPR1_Active
  WPR5_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR5_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR5_Active.set
      TEST_REPORT_NAME: EA31337-WPR5_Active
  WPR15_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR15_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR15_Active.set
      TEST_REPORT_NAME: EA31337-WPR15_Active
  WPR30_Active:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR30_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR30_Active.set
      TEST_REPORT_NAME: EA31337-WPR30_Active
