version: '3.4'
services:
  SAR_TrailingStopMethod:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR_TrailingStopMethod
      RUN_ON_SET: set_opt_params SAR_TrailingStopMethod 1 -27 0
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EURUSD/EA31337-SAR_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-SAR_TrailingStopMethod
  SAR_TrailingProfitMethod:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR_TrailingProfitMethod
      RUN_ON_SET: set_opt_params SAR_TrailingProfitMethod 1 -27 0
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EURUSD/EA31337-SAR_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-SAR_TrailingProfitMethod
